### ISSUE TITLE
Application crushes after changing screen orientation twice

### ISSUE THREAD

**Issue by paulgrape** [muzzy404/ExpensesAdvisor#2]
Actions:
- log in to application
- change screen orientation to landscape mode
- change screen orientation back to portrait mode

Actual Result:
Application crushes

Expected Result:
Landscape mode is disable for the whole application

**Comment by muzzy404** [comment]
[fixed](https://github.com/muzzy404/ExpensesAdvisor/tree/3e7d4faee929a0e4beb0154a8104936b6bda1e87)
